version: '3'
services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 80:3000
    environment: 
      - REACT_APP_URI_FILM_SERVICE=http://movieservice:3002
      - REACT_APP_URI_SHOP_SERVICE=http://shopservice:3001
      - REACT_APP_URI_USER_SERVICE=http://userservice:3003
      - NODE_ENV=production
  movieservice:
    build:
      context: ./services/uniflix-movieservice
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment: 
      - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
      - NODE_ENV=production
  shopservice:
    build:
      context: ./services/uniflix-shopservice
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment: 
      - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
      - USER_SERVICE_URI=http://userservice:3003/rest
      - MOVIE_SERVICE_URI=http://movieservice:3002/rest/movies
      - NODE_ENV=production
  userservice:
    build:
      context: ./services/uniflix-userservice
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    environment: 
      - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
      - TOKEN_SECRET=thisismynewcourse
      - PORT=3003
      - NODE_ENV=production
  mongodb:
    image: mongo:5.0
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      - NODE_ENV=development
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
