version: '3'
services:
  # webapp:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ".:/usr/src/app"
  #   environment: 
  #     - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
  #     - TOKEN_SECRET=thisismynewcourse
  #     - NODE_ENV=production
  mongodb:
    image: mongo:5.0
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      - NODE_ENV=development
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

    